// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// scaleNotCenterFast
arma::sp_mat scaleNotCenterFast(arma::sp_mat x);
RcppExport SEXP _macoskoliger_scaleNotCenterFast(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleNotCenterFast(x));
    return rcpp_result_gen;
END_RCPP
}
// rowMeansFast
NumericVector rowMeansFast(arma::sp_mat x);
RcppExport SEXP _macoskoliger_rowMeansFast(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rowMeansFast(x));
    return rcpp_result_gen;
END_RCPP
}
// rowVarsFast
NumericVector rowVarsFast(arma::sp_mat x, NumericVector means);
RcppExport SEXP _macoskoliger_rowVarsFast(SEXP xSEXP, SEXP meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    rcpp_result_gen = Rcpp::wrap(rowVarsFast(x, means));
    return rcpp_result_gen;
END_RCPP
}
// solveNNLS
arma::mat solveNNLS(const arma::mat& C, const arma::mat& B);
RcppExport SEXP _macoskoliger_solveNNLS(SEXP CSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(solveNNLS(C, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_macoskoliger_scaleNotCenterFast", (DL_FUNC) &_macoskoliger_scaleNotCenterFast, 1},
    {"_macoskoliger_rowMeansFast", (DL_FUNC) &_macoskoliger_rowMeansFast, 1},
    {"_macoskoliger_rowVarsFast", (DL_FUNC) &_macoskoliger_rowVarsFast, 2},
    {"_macoskoliger_solveNNLS", (DL_FUNC) &_macoskoliger_solveNNLS, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_macoskoliger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
